# Generated by Django 3.2 on 2021-04-23 12:03

import Inventory.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20210422_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('opening', models.TimeField()),
                ('closing', models.TimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.store')),
            ],
        ),
        migrations.DeleteModel(
            name='Opening',
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'sale', 'verbose_name_plural': 'sales'},
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.ImageField(blank=True, upload_to=Inventory.models.product_code_directory_path),
        ),
    ]
