# Generated by Django 3.2 on 2021-04-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_auto_20210424_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcode',
            name='inventory',
        ),
    ]
