# Generated by Django 3.2.8 on 2021-10-29 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inventory', '0006_alter_barcode_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='store',
            new_name='business',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='store',
            new_name='business',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='store',
            new_name='business',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='store',
            new_name='business',
        ),
        migrations.RenameField(
            model_name='relation',
            old_name='store',
            new_name='business',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='store',
            new_name='business',
        ),
        migrations.RenameField(
            model_name='timing',
            old_name='store',
            new_name='business',
        ),
        migrations.RenameModel(
            old_name='Store',
            new_name='Business',
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=256)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Inventory.business')),
            ],
        ),
    ]
