# Generated by Django 3.2.8 on 2021-10-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='keyword',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
