# Generated by Django 3.2.8 on 2021-11-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20211111_2354'),
        ('Barcode', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Barcode',
            new_name='SKU',
        ),
    ]
