# Generated by Django 3.2.8 on 2022-02-01 18:05

import Business.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20220201_2335'),
        ('Barcode', '0002_rename_barcode_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=14, unique=True)),
                ('barcodeimage', models.ImageField(blank=True, upload_to=Business.utils.product_code_directory_path)),
                ('qrcodeimage', models.ImageField(blank=True, upload_to=Business.utils.product_code_directory_path)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
            ],
        ),
    ]
